# Generated by Django 3.0.3 on 2020-02-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=30)),
                ('degree', models.CharField(max_length=120)),
                ('gpa', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('courses', models.TextField()),
            ],
        ),
    ]
