# Generated by Django 3.0.3 on 2020-03-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_award_project_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
